insert into vehicles (id, make, model, type, location) values (1, 'Hyundai', 'Elantra', 'pickup truck', 'Mumbai');
insert into vehicles (id, make, model, type, location) values (2, 'Scion', 'xD', 'hatchback', 'Mumbai');
insert into vehicles (id, make, model, type, location) values (3, 'Toyota', 'Highlander Hybrid', 'hatchback', 'Philadelphia');
insert into vehicles (id, make, model, type, location) values (4, 'Chevrolet', 'Silverado', 'hatchback', 'Philadelphia');
insert into vehicles (id, make, model, type, location) values (5, 'Ford', 'Ranger', 'van', 'Philadelphia');
insert into vehicles (id, make, model, type, location) values (6, 'Porsche', '911', 'van', 'Philadelphia');
insert into vehicles (id, make, model, type, location) values (7, 'Mercury', 'Grand Marquis', 'convertible', 'Philadelphia');
insert into vehicles (id, make, model, type, location) values (8, 'Mercedes-Benz', 'S-Class', 'van', 'Philadelphia');
insert into vehicles (id, make, model, type, location) values (9, 'GMC', 'Envoy XL', 'hatchback', 'Philadelphia');
insert into vehicles (id, make, model, type, location) values (10, 'Kia', 'Sedona', 'sedan', 'Mumbai');
insert into vehicles (id, make, model, type, location) values (11, 'Kia', 'Rio', 'SUV', 'Mumbai');
insert into vehicles (id, make, model, type, location) values (12, 'Chevrolet', 'Impala', 'SUV', 'Philadelphia');
insert into vehicles (id, make, model, type, location) values (13, 'GMC', 'Terrain', 'compact', 'Philadelphia');
insert into vehicles (id, make, model, type, location) values (14, 'Volvo', 'XC90', 'pickup truck', 'Philadelphia');
insert into vehicles (id, make, model, type, location) values (15, 'Lexus', 'RX', 'sedan', 'Mumbai');
insert into vehicles (id, make, model, type, location) values (16, 'Volkswagen', 'Eos', 'SUV', 'Philadelphia');
insert into vehicles (id, make, model, type, location) values (17, 'Mercedes-Benz', 'SL-Class', 'compact', 'Philadelphia');
insert into vehicles (id, make, model, type, location) values (18, 'Jaguar', 'XK', 'sedan', 'Mumbai');
insert into vehicles (id, make, model, type, location) values (19, 'Honda', 'Civic', 'compact', 'Philadelphia');
insert into vehicles (id, make, model, type, location) values (20, 'Mercury', 'Villager', 'SUV', 'Mumbai');
insert into vehicles (id, make, model, type, location) values (21, 'Lexus', 'LX', 'sedan', 'Mumbai');
insert into vehicles (id, make, model, type, location) values (22, 'Mitsubishi', 'Galant', 'hatchback', 'Philadelphia');
insert into vehicles (id, make, model, type, location) values (23, 'Acura', 'RL', 'compact', 'Philadelphia');
insert into vehicles (id, make, model, type, location) values (24, 'Subaru', 'Impreza', 'van', 'Philadelphia');
insert into vehicles (id, make, model, type, location) values (25, 'Lexus', 'ES', 'pickup truck', 'Philadelphia');
insert into vehicles (id, make, model, type, location) values (26, 'Mazda', 'MX-5', 'SUV', 'Philadelphia');
insert into vehicles (id, make, model, type, location) values (27, 'Buick', 'Park Avenue', 'minivan', 'Mumbai');
insert into vehicles (id, make, model, type, location) values (28, 'Jeep', 'Liberty', 'convertible', 'Philadelphia');
insert into vehicles (id, make, model, type, location) values (29, 'Chevrolet', '2500', 'pickup truck', 'Mumbai');
insert into vehicles (id, make, model, type, location) values (30, 'Toyota', 'Supra', 'sedan', 'Mumbai');
