insert into vehicles (id, make, model, type, location, price_per_day) values (1, 'Volkswagen', 'Jetta', 'Car', 'Cancún', 61);
insert into vehicles (id, make, model, type, location, price_per_day) values (2, 'Pontiac', 'Montana', 'Truck', 'Philadelphia', 62);
insert into vehicles (id, make, model, type, location, price_per_day) values (3, 'Cadillac', 'STS', 'SUV', 'Philadelphia', 104);
insert into vehicles (id, make, model, type, location, price_per_day) values (4, 'Pontiac', 'Bonneville', 'Van', 'Philadelphia', 92);
insert into vehicles (id, make, model, type, location, price_per_day) values (5, 'Ford', 'Transit Connect', 'Truck', 'Cancún', 112);
insert into vehicles (id, make, model, type, location, price_per_day) values (6, 'Ford', 'LTD Crown Victoria', 'Van', 'Cancún', 93);
insert into vehicles (id, make, model, type, location, price_per_day) values (7, 'Volvo', 'V70', 'SUV', 'Cancún', 88);
insert into vehicles (id, make, model, type, location, price_per_day) values (8, 'Mercury', 'Capri', 'Van', 'Philadelphia', 91);
insert into vehicles (id, make, model, type, location, price_per_day) values (9, 'Mazda', 'Mazda6', 'Car', 'Cancún', 90);
insert into vehicles (id, make, model, type, location, price_per_day) values (10, 'Nissan', 'Frontier', 'Van', 'Cancún', 52);
insert into vehicles (id, make, model, type, location, price_per_day) values (11, 'Dodge', 'Journey', 'SUV', 'Philadelphia', 69);
insert into vehicles (id, make, model, type, location, price_per_day) values (12, 'Pontiac', 'Bonneville', 'SUV', 'Cancún', 105);
insert into vehicles (id, make, model, type, location, price_per_day) values (13, 'Nissan', 'Sentra', 'SUV', 'Philadelphia', 59);
insert into vehicles (id, make, model, type, location, price_per_day) values (14, 'GMC', '3500 Club Coupe', 'Car', 'Cancún', 117);
insert into vehicles (id, make, model, type, location, price_per_day) values (15, 'Nissan', 'Sentra', 'SUV', 'Philadelphia', 66);
insert into vehicles (id, make, model, type, location, price_per_day) values (16, 'Ford', 'F-Series', 'Truck', 'Philadelphia', 36);
insert into vehicles (id, make, model, type, location, price_per_day) values (17, 'Honda', 'Ridgeline', 'SUV', 'Cancún', 37);
insert into vehicles (id, make, model, type, location, price_per_day) values (18, 'Ford', 'Bronco', 'Car', 'Philadelphia', 74);
insert into vehicles (id, make, model, type, location, price_per_day) values (19, 'GMC', 'Vandura 2500', 'Van', 'Philadelphia', 112);
insert into vehicles (id, make, model, type, location, price_per_day) values (20, 'Cadillac', 'CTS', 'Truck', 'Philadelphia', 58);
insert into vehicles (id, make, model, type, location, price_per_day) values (21, 'Mazda', 'Protege', 'SUV', 'Philadelphia', 64);
insert into vehicles (id, make, model, type, location, price_per_day) values (22, 'Buick', 'Century', 'SUV', 'Philadelphia', 96);
insert into vehicles (id, make, model, type, location, price_per_day) values (23, 'Toyota', 'Prius', 'Truck', 'Cancún', 75);
insert into vehicles (id, make, model, type, location, price_per_day) values (24, 'Land Rover', 'Range Rover', 'SUV', 'Cancún', 70);
insert into vehicles (id, make, model, type, location, price_per_day) values (25, 'Lincoln', 'Mark VIII', 'Truck', 'Philadelphia', 80);
insert into vehicles (id, make, model, type, location, price_per_day) values (26, 'Land Rover', 'Sterling', 'Truck', 'Cancún', 58);
insert into vehicles (id, make, model, type, location, price_per_day) values (27, 'BMW', 'M3', 'Car', 'Cancún', 84);
insert into vehicles (id, make, model, type, location, price_per_day) values (28, 'GMC', '2500', 'Car', 'Cancún', 37);
insert into vehicles (id, make, model, type, location, price_per_day) values (29, 'Toyota', 'Solara', 'SUV', 'Philadelphia', 102);
insert into vehicles (id, make, model, type, location, price_per_day) values (30, 'Pontiac', 'Torrent', 'Truck', 'Cancún', 72);
insert into vehicles (id, make, model, type, location, price_per_day) values (31, 'Pontiac', 'Grand Am', 'Truck', 'Cancún', 80);
insert into vehicles (id, make, model, type, location, price_per_day) values (32, 'Ford', 'F150', 'Car', 'Cancún', 99);
insert into vehicles (id, make, model, type, location, price_per_day) values (33, 'Pontiac', 'Sunfire', 'Car', 'Philadelphia', 63);
insert into vehicles (id, make, model, type, location, price_per_day) values (34, 'Mazda', 'Tribute', 'Van', 'Philadelphia', 99);
insert into vehicles (id, make, model, type, location, price_per_day) values (35, 'Honda', 'CR-V', 'Van', 'Cancún', 39);
insert into vehicles (id, make, model, type, location, price_per_day) values (36, 'Nissan', 'Maxima', 'Van', 'Philadelphia', 71);
insert into vehicles (id, make, model, type, location, price_per_day) values (37, 'BMW', '530', 'Truck', 'Cancún', 39);
insert into vehicles (id, make, model, type, location, price_per_day) values (38, 'Bentley', 'Azure', 'Car', 'Philadelphia', 48);
insert into vehicles (id, make, model, type, location, price_per_day) values (39, 'Ford', 'Explorer', 'Truck', 'Cancún', 48);
insert into vehicles (id, make, model, type, location, price_per_day) values (40, 'Kia', 'Spectra5', 'SUV', 'Philadelphia', 101);
insert into vehicles (id, make, model, type, location, price_per_day) values (41, 'BMW', 'M5', 'SUV', 'Cancún', 44);
insert into vehicles (id, make, model, type, location, price_per_day) values (42, 'Mercedes-Benz', 'SLK55 AMG', 'Van', 'Cancún', 31);
insert into vehicles (id, make, model, type, location, price_per_day) values (43, 'Ferrari', '599 GTB Fiorano', 'SUV', 'Cancún', 89);
insert into vehicles (id, make, model, type, location, price_per_day) values (44, 'Lexus', 'IS-F', 'Truck', 'Philadelphia', 91);
insert into vehicles (id, make, model, type, location, price_per_day) values (45, 'Suzuki', 'Vitara', 'SUV', 'Philadelphia', 91);
insert into vehicles (id, make, model, type, location, price_per_day) values (46, 'Mitsubishi', 'Eclipse', 'SUV', 'Cancún', 92);
insert into vehicles (id, make, model, type, location, price_per_day) values (47, 'Ford', 'Ranger', 'Car', 'Cancún', 40);
insert into vehicles (id, make, model, type, location, price_per_day) values (48, 'Honda', 'Accord', 'Truck', 'Philadelphia', 45);
insert into vehicles (id, make, model, type, location, price_per_day) values (49, 'Dodge', 'Ram', 'Van', 'Cancún', 49);
insert into vehicles (id, make, model, type, location, price_per_day) values (50, 'Mercedes-Benz', 'SL-Class', 'Van', 'Philadelphia', 40);
insert into vehicles (id, make, model, type, location, price_per_day) values (51, 'GMC', 'Savana', 'Van', 'Cancún', 64);
insert into vehicles (id, make, model, type, location, price_per_day) values (52, 'Buick', 'Rainier', 'SUV', 'Philadelphia', 84);
insert into vehicles (id, make, model, type, location, price_per_day) values (53, 'Nissan', 'Frontier', 'Car', 'Philadelphia', 96);
insert into vehicles (id, make, model, type, location, price_per_day) values (54, 'Pontiac', 'Grand Prix', 'Van', 'Philadelphia', 36);
insert into vehicles (id, make, model, type, location, price_per_day) values (55, 'Toyota', 'Camry', 'Truck', 'Philadelphia', 46);
insert into vehicles (id, make, model, type, location, price_per_day) values (56, 'Mitsubishi', 'Mirage', 'Van', 'Cancún', 79);
insert into vehicles (id, make, model, type, location, price_per_day) values (57, 'Chevrolet', 'Suburban 1500', 'Car', 'Philadelphia', 76);
insert into vehicles (id, make, model, type, location, price_per_day) values (58, 'Suzuki', 'Vitara', 'Van', 'Cancún', 44);
insert into vehicles (id, make, model, type, location, price_per_day) values (59, 'Mazda', 'Millenia', 'Van', 'Philadelphia', 37);
insert into vehicles (id, make, model, type, location, price_per_day) values (60, 'Volvo', 'S40', 'Car', 'Cancún', 70);
insert into vehicles (id, make, model, type, location, price_per_day) values (61, 'Chevrolet', 'Suburban 1500', 'Truck', 'Philadelphia', 115);
insert into vehicles (id, make, model, type, location, price_per_day) values (62, 'Ford', 'Econoline E150', 'Van', 'Philadelphia', 82);
insert into vehicles (id, make, model, type, location, price_per_day) values (63, 'Ford', 'Taurus', 'SUV', 'Philadelphia', 61);
insert into vehicles (id, make, model, type, location, price_per_day) values (64, 'GMC', 'Jimmy', 'Truck', 'Philadelphia', 91);
insert into vehicles (id, make, model, type, location, price_per_day) values (65, 'Acura', 'TSX', 'Truck', 'Philadelphia', 31);
insert into vehicles (id, make, model, type, location, price_per_day) values (66, 'Audi', 'A8', 'SUV', 'Cancún', 39);
insert into vehicles (id, make, model, type, location, price_per_day) values (67, 'Smart', 'Fortwo', 'Truck', 'Philadelphia', 70);
insert into vehicles (id, make, model, type, location, price_per_day) values (68, 'Mazda', 'Mazda6', 'Van', 'Philadelphia', 125);
insert into vehicles (id, make, model, type, location, price_per_day) values (69, 'Mercedes-Benz', 'CLK-Class', 'Van', 'Cancún', 83);
insert into vehicles (id, make, model, type, location, price_per_day) values (70, 'Audi', 'A6', 'SUV', 'Philadelphia', 86);
insert into vehicles (id, make, model, type, location, price_per_day) values (71, 'Hyundai', 'Accent', 'Truck', 'Philadelphia', 40);
insert into vehicles (id, make, model, type, location, price_per_day) values (72, 'Mercury', 'Lynx', 'Car', 'Philadelphia', 55);
insert into vehicles (id, make, model, type, location, price_per_day) values (73, 'Isuzu', 'Ascender', 'Van', 'Cancún', 64);
insert into vehicles (id, make, model, type, location, price_per_day) values (74, 'Mitsubishi', 'Galant', 'Van', 'Philadelphia', 70);
insert into vehicles (id, make, model, type, location, price_per_day) values (75, 'Suzuki', 'SX4', 'SUV', 'Philadelphia', 112);
insert into vehicles (id, make, model, type, location, price_per_day) values (76, 'Dodge', 'Colt', 'SUV', 'Philadelphia', 77);
insert into vehicles (id, make, model, type, location, price_per_day) values (77, 'Porsche', 'Panamera', 'Truck', 'Cancún', 118);
insert into vehicles (id, make, model, type, location, price_per_day) values (78, 'Toyota', 'Venza', 'SUV', 'Cancún', 69);
insert into vehicles (id, make, model, type, location, price_per_day) values (79, 'Chrysler', 'Imperial', 'SUV', 'Philadelphia', 43);
insert into vehicles (id, make, model, type, location, price_per_day) values (80, 'Lexus', 'GX', 'Truck', 'Cancún', 42);
insert into vehicles (id, make, model, type, location, price_per_day) values (81, 'Pontiac', 'Firebird Formula', 'Truck', 'Cancún', 102);
insert into vehicles (id, make, model, type, location, price_per_day) values (82, 'Audi', 'Cabriolet', 'Car', 'Cancún', 86);
insert into vehicles (id, make, model, type, location, price_per_day) values (83, 'Dodge', 'Durango', 'SUV', 'Philadelphia', 119);
insert into vehicles (id, make, model, type, location, price_per_day) values (84, 'Ford', 'Transit Connect', 'Car', 'Philadelphia', 31);
insert into vehicles (id, make, model, type, location, price_per_day) values (85, 'Geo', 'Prizm', 'Car', 'Philadelphia', 118);
insert into vehicles (id, make, model, type, location, price_per_day) values (86, 'BMW', 'X5', 'Car', 'Philadelphia', 106);
insert into vehicles (id, make, model, type, location, price_per_day) values (87, 'Honda', 'Insight', 'Car', 'Cancún', 62);
insert into vehicles (id, make, model, type, location, price_per_day) values (88, 'Toyota', 'FJ Cruiser', 'Truck', 'Cancún', 108);
insert into vehicles (id, make, model, type, location, price_per_day) values (89, 'Suzuki', 'Verona', 'SUV', 'Cancún', 124);
insert into vehicles (id, make, model, type, location, price_per_day) values (90, 'Chevrolet', 'Lumina APV', 'SUV', 'Cancún', 76);
insert into vehicles (id, make, model, type, location, price_per_day) values (91, 'Kia', 'Spectra', 'Truck', 'Philadelphia', 55);
insert into vehicles (id, make, model, type, location, price_per_day) values (92, 'Lexus', 'RX', 'Car', 'Cancún', 31);
insert into vehicles (id, make, model, type, location, price_per_day) values (93, 'Oldsmobile', 'Custom Cruiser', 'Car', 'Philadelphia', 104);
insert into vehicles (id, make, model, type, location, price_per_day) values (94, 'Chevrolet', 'Cavalier', 'Car', 'Philadelphia', 109);
insert into vehicles (id, make, model, type, location, price_per_day) values (95, 'Kia', 'Sportage', 'Truck', 'Philadelphia', 120);
insert into vehicles (id, make, model, type, location, price_per_day) values (96, 'Mitsubishi', 'Tredia', 'Truck', 'Cancún', 72);
insert into vehicles (id, make, model, type, location, price_per_day) values (97, 'GMC', 'Sierra 3500', 'Truck', 'Cancún', 102);
insert into vehicles (id, make, model, type, location, price_per_day) values (98, 'Ford', 'Mustang', 'SUV', 'Cancún', 92);
insert into vehicles (id, make, model, type, location, price_per_day) values (99, 'Dodge', 'Challenger', 'SUV', 'Philadelphia', 35);
insert into vehicles (id, make, model, type, location, price_per_day) values (100, 'Plymouth', 'Colt Vista', 'Car', 'Cancún', 54);
