insert into vehicles (id, make, model, type, location, reservation_id) values (1, 'Plymouth', 'Breeze', 'crossover', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (2, 'Mazda', '626', 'van', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (3, 'Nissan', 'Armada', 'minivan', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (4, 'GMC', 'Sierra 1500', 'minivan', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (5, 'Cadillac', 'DTS', 'minivan', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (6, 'Nissan', 'Quest', 'hatchback', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (7, 'Volvo', 'C70', 'sedan', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (8, 'Chevrolet', 'Express 1500', 'hatchback', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (9, 'Mitsubishi', '3000GT', 'minivan', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (10, 'Pontiac', 'Sunbird', 'hatchback', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (11, 'Toyota', 'RAV4', 'hatchback', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (12, 'Ford', 'F250', 'suv', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (13, 'Hyundai', 'Tucson', 'crossover', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (14, 'Chevrolet', 'Express 3500', 'hatchback', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (15, 'Scion', 'xB', 'hatchback', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (16, 'Pontiac', 'Bonneville', 'coupe', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (17, 'GMC', 'Canyon', 'hatchback', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (18, 'Chevrolet', 'Lumina APV', 'compact', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (19, 'Nissan', 'Quest', 'suv', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (20, 'Chevrolet', 'Malibu', 'minivan', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (21, 'Jeep', 'Patriot', 'hatchback', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (22, 'Ford', 'Windstar', 'convertible', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (23, 'Buick', 'Riviera', 'coupe', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (24, 'Land Rover', 'Range Rover', 'crossover', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (25, 'Pontiac', 'Grand Prix', 'compact', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (26, 'Mazda', '929', 'hatchback', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (27, 'Suzuki', 'Swift', 'van', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (28, 'Ford', 'Thunderbird', 'crossover', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (29, 'Hyundai', 'Elantra', 'compact', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (30, 'Kia', 'Sedona', 'compact', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (31, 'Chevrolet', 'Suburban 2500', 'suv', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (32, 'Plymouth', 'Voyager', 'convertible', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (33, 'Ford', 'Fusion', 'convertible', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (34, 'Hummer', 'H1', 'suv', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (35, 'Pontiac', 'Vibe', 'van', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (36, 'Lincoln', 'MKZ', 'coupe', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (37, 'Chevrolet', 'Caprice', 'convertible', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (38, 'Mazda', 'MX-6', 'crossover', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (39, 'Mitsubishi', 'Challenger', 'coupe', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (40, 'BMW', '7 Series', 'van', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (41, 'Mazda', '323', 'coupe', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (42, 'Mercury', 'Villager', 'crossover', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (43, 'Isuzu', 'Trooper', 'van', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (44, 'GMC', 'Savana 2500', 'crossover', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (45, 'Suzuki', 'Equator', 'crossover', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (46, 'Ford', 'Explorer', 'crossover', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (47, 'Subaru', 'SVX', 'convertible', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (48, 'Mitsubishi', '3000GT', 'minivan', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (49, 'Nissan', 'GT-R', 'suv', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (50, 'Chevrolet', 'Impala SS', 'sedan', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (51, 'Chevrolet', 'Traverse', 'sedan', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (52, 'Mazda', 'Miata MX-5', 'compact', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (53, 'Mitsubishi', 'Diamante', 'van', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (54, 'Mercedes-Benz', 'M-Class', 'compact', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (55, 'Oldsmobile', 'Silhouette', 'coupe', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (56, 'BMW', '3 Series', 'van', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (57, 'Mitsubishi', 'Diamante', 'convertible', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (58, 'Nissan', 'Maxima', 'sedan', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (59, 'Chevrolet', 'Corsica', 'coupe', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (60, 'Chevrolet', 'Aveo', 'convertible', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (61, 'Scion', 'iQ', 'compact', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (62, 'Pontiac', 'Sunfire', 'van', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (63, 'Jeep', 'Wrangler', 'hatchback', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (64, 'Pontiac', 'Grand Prix', 'minivan', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (65, 'Cadillac', 'Eldorado', 'convertible', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (66, 'Suzuki', 'Grand Vitara', 'coupe', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (67, 'Pontiac', 'GTO', 'convertible', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (68, 'Porsche', 'Cayenne', 'convertible', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (69, 'Volvo', 'C70', 'hatchback', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (70, 'GMC', 'Sierra', 'sedan', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (71, 'Nissan', 'Murano', 'sedan', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (72, 'Mercedes-Benz', 'SLK-Class', 'hatchback', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (73, 'Ford', 'E250', 'hatchback', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (74, 'Lamborghini', 'Murciélago', 'crossover', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (75, 'Toyota', 'T100 Xtra', 'minivan', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (76, 'Ford', 'Expedition', 'hatchback', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (77, 'Land Rover', 'Range Rover', 'compact', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (78, 'Infiniti', 'QX56', 'coupe', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (79, 'Porsche', '928', 'coupe', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (80, 'Dodge', 'Grand Caravan', 'sedan', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (81, 'Ford', 'Probe', 'suv', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (82, 'Volkswagen', 'GTI', 'minivan', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (83, 'Chevrolet', 'Impala', 'hatchback', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (84, 'Honda', 'Pilot', 'compact', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (85, 'Mitsubishi', 'Truck', 'suv', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (86, 'Chevrolet', 'Malibu', 'minivan', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (87, 'Mitsubishi', 'Montero Sport', 'hatchback', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (88, 'Volkswagen', 'New Beetle', 'hatchback', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (89, 'Chevrolet', 'Camaro', 'minivan', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (90, 'Bentley', 'Mulsanne', 'minivan', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (91, 'Buick', 'LeSabre', 'hatchback', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (92, 'Toyota', 'Celica', 'crossover', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (93, 'Cadillac', 'Escalade', 'coupe', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (94, 'Acura', 'RSX', 'suv', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (95, 'Lexus', 'LS', 'convertible', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (96, 'Hyundai', 'Veloster', 'suv', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (97, 'GMC', 'Savana 1500', 'convertible', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (98, 'Kia', 'Sedona', 'suv', 'Philadelphia', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (99, 'Toyota', 'RAV4', 'coupe', 'Mumbai', null);
insert into vehicles (id, make, model, type, location, reservation_id) values (100, 'Acura', 'MDX', 'convertible', 'Mumbai', null);
